### PR TITLE
Create 725.java

### LINKED ISSUE #534: Leetcode Question Number 725
Leetcode Question Number 725 soultion needs to be added in the repo . 
 The link for the question is [this](https://leetcode.com/problems/split-linked-list-in-parts).
 Accepted Languages C++ / JAVA . 
 You Only need to add the  class Solution in the file. 
 Make Sure you have read the contributions guidelines before creating an PR.

### PR DESCRIPTION
**Pull request by shubhanshuj22**
Fixes #534 {Leetcode Question Number 725}

My code sample is in : 
- [ ] CPP
- [X] Java 

Screenshot of working code sample  : 

## Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] My code sample is formatted and works correctly 

[Contributor Guide]: https://github.com/amanv8060/Leetcode-Questions/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Comment by amanv8060** [comment]
Update pr comment with issue number and ss. Thanks!

**Comment by shubhanshuj22** [comment]
Updated please check

**Comment by amanv8060** [comment]
Can you add the ss as well? Thanks!

**Comment by amanv8060** [comment]
Seeing no response, I will be closing this. Feel Free to open a new pr.

**Pull request closed without merging**
