### PR TITLE
Adding solution for 1941.

### LINKED ISSUE #1652: Leetcode Question Number 1941
Leetcode Question Number 1941 solution needs to be added in the repo . 
 The link for the question is [this](https://leetcode.com/problems/check-if-all-characters-have-equal-number-of-occurrences).
 Accepted Languages C++ / JAVA . 
 You Only need to add the  class Solution in the file. 
 Make Sure you have read the contributions guidelines before creating an PR.

### PR DESCRIPTION
**Pull request by hitesh1906**
Fixes #1652

My code sample is in : 
- [✔ ] CPP
- [ ] Java 

Screenshot of working code sample  : 

image

## Checklist

- [✔ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [✔ ] My code sample is formatted and works correctly 

[Contributor Guide]: https://github.com/amanv8060/Leetcode-Questions/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Comment by hitesh1906** [comment]
I have completed issue no 1941. Please merge this in your repository.
My code is faster than 100%. Memory usage is less than  99.28% of c++ users.

**Comment by amanv8060** [comment]
@hitesh1906 Please update the issue number in the original pr comment  , and format the code

**Comment by hitesh1906** [comment]
I have updated issue no but how to format the code? can you please help me with this?

**Comment by hitesh1906** [comment]
I have updated the format can you please check the ones.
Thankyou.

> @hitesh1906 Please update the issue number in the original pr comment, and format the code

**Pull request merged**
