### PR TITLE
Problem 9 Solved

### LINKED ISSUE #9: Leetcode Question Number 9
Leetcode Question Number 9 soultion needs to be added in the repo . 
 The link for the question is [this](https://leetcode.com/problems/palindrome-number).
 Accepted Languages C++ / JAVA . 
 You Only need to add the  class Solution in the file. 
 Make Sure you have read the contributions guidelines before creating an PR.

### PR DESCRIPTION
**Pull request by aakash345**
Fixes #9  Adding solution for 9

My code sample is in : 
- [x] CPP 
- [ ] Java 
Screenshot of working code sample  

//Attach screenshot of successful submission 
9cpp

## Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My code sample is formatted and works correctly 

[Contributor Guide]: https://github.com/amanv8060/Leetcode-Questions/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Comment by amanv8060** [comment]
Add issue number in the comment after `Fixes`

**Comment by aakash345** [comment]
> Add issue number in the comment after `Fixes`

**Comment by aakash345** [comment]
> Add issue number in the comment after `Fixes`

Done

**Comment by amanv8060** [comment]
Thanks for your contribution, the issue that you are trying to contribute to has been already assigned to another person. I am closing this pr in favour of the accepted pr.

Read contributing guidelines for contributing further.

**Pull request closed without merging**
