### PR TITLE
Adding solution for 1876.

### LINKED ISSUE #1604: Leetcode Question Number 1876
Leetcode Question Number 1876 solution needs to be added in the repo . 
 The link for the question is [this](https://leetcode.com/problems/substrings-of-size-three-with-distinct-characters).
 Accepted Languages C++ / JAVA . 
 You Only need to add the  class Solution in the file. 
 Make Sure you have read the contributions guidelines before creating an PR.

### PR DESCRIPTION
**Pull request by hitesh1906**
Fixes #1604

My code sample is in : 
- [✔ ] CPP
- [ ] Java 

Screenshot of working code sample  : 

image

## Checklist

- [✔ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [✔ ] My code sample is formatted and works correctly 

[Contributor Guide]: https://github.com/amanv8060/Leetcode-Questions/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Comment by hitesh1906** [comment]
I have completed question no 1876. Please merge this in your repository.
My code is faster than 100%. and Memory usage is less than 39.84% of c++ users.

**Comment by amanv8060** [comment]
needs formatting

**Comment by hitesh1906** [comment]
> needs formatting

I have updated please check the ones.

**Comment by hitesh1906** [comment]
> > needs formatting
> 
> I have updated please check the ones.

Please check again.

**Pull request merged**
