### PR TITLE
Added code for 3 leetcode problem

### LINKED ISSUE #3: Leetcode Question Number 3
Leetcode Question Number 3 soultion needs to be added in the repo . 
 The link for the question is [this](https://leetcode.com/problems/longest-substring-without-repeating-characters).
 Accepted Languages C++ / JAVA . 
 You Only need to add the  class Solution in the file. 
 Make Sure you have read the contributions guidelines before creating an PR.

### PR DESCRIPTION
**Pull request by Khushi-agarwal**
Fixes #3 

My code sample is in : 
- [x] CPP
- [ ] Java 

Screenshot of working code sample  : 

image

## Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My code sample is formatted and works correctly 

[Contributor Guide]: https://github.com/amanv8060/Leetcode-Questions/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Comment by amanv8060** [comment]
Update issue number above

**Comment by Khushi-agarwal** [comment]
> Update issue number in above comment

@amanv8060 done

**Comment by amanv8060** [comment]
@Khushi-agarwal please format the file as well, instructions to do so is in the contributing guidelines. (You can use the website mentioned over there , if you don't have clang-format installed)

**Comment by Khushi-agarwal** [comment]
@amanv8060 I have formatted the file according to the instructions.

**Comment by amanv8060** [comment]
@Khushi-agarwal format check is failing .

**Comment by Khushi-agarwal** [comment]
@amanv8060 I am working on it

**Pull request closed without merging**
