### PR TITLE
Added solution for 1967

### LINKED ISSUE #1680: Leetcode Question Number 1967
Leetcode Question Number 1967 solution needs to be added in the repo . 
 The link for the question is [this](https://leetcode.com/problems/number-of-strings-that-appear-as-substrings-in-word).
 Accepted Languages C++ / JAVA . 
 You Only need to add the  class Solution in the file. 
 Make Sure you have read the contributions guidelines before creating an PR.

### PR DESCRIPTION
**Pull request by classerase**
Fixes #1680

My code sample is in : 
- [ ] CPP
- [x] Java 

Screenshot of working code sample  : 

image

## Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My code sample is formatted and works correctly 

[Contributor Guide]: https://github.com/amanv8060/Leetcode-Questions/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Comment by classerase** [comment]
sorry for re-opening btw, i was tryna fix the 4.cpp bc its already in a different PR but i couldnt..

**Comment by classerase** [comment]
#1680

**Comment by classerase** [comment]
hopefully that fixed the conflict

**Review by amanv8060 — CHANGES_REQUESTED** [review]
(Edit: )Delete 1st empty line from 4.cpp

**Comment by classerase** [comment]
let me know if anything else needs to be changed

**Review by amanv8060 — APPROVED** [review]

**Pull request merged**
