### PR TITLE
leetcode 32

### PR DESCRIPTION
**Pull request by Krish6170**
Fixes #{Insert your issue number here}
32

My code sample is in : 
- [🗸 ] CPP
- [ ] Java 

Screenshot of working code sample  : 

leet2

## Checklist

- [🗸 ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [🗸 ] My code sample is formatted and works correctly 

[Contributor Guide]: https://github.com/amanv8060/Leetcode-Questions/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Review by Krish6170 — COMMENTED** [review]
please merge

**Comment by amanv8060** [comment]
Please update your issue comment appropriately, also add one solution at once.

**Comment by Krish6170** [comment]
done

**Comment by Krish6170** [comment]
> Please update your issue comment appropriately, also add one solution at once.

please update now

**Review by amanv8060 — CHANGES_REQUESTED** [review]
@Krish6170 Thanks for your contribution. Please have a look at [this](https://github.com/amanv8060/Leetcode-Questions/pull/1736) pr, on how to edit the pr comment. Also, you need to format your code.

**Pull request closed without merging**
