### PR TITLE
Solution_44

### LINKED ISSUE #44: Leetcode Question Number 44
Leetcode Question Number 44 soultion needs to be added in the repo . 
 The link for the question is [this](https://leetcode.com/problems/wildcard-matching).
 Accepted Languages C++ / JAVA . 
 You Only need to add the  class Solution in the file. 
 Make Sure you have read the contributions guidelines before creating an PR.

### PR DESCRIPTION
**Pull request by sourav2b**
Fixes #44 

My code sample is in : 
- [x] CPP
- [ ] Java 

Screenshot of working code sample  : 

image

## Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My code sample is formatted and works correctly 

[Contributor Guide]: https://github.com/amanv8060/Leetcode-Questions/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Review by amanv8060 — CHANGES_REQUESTED** [review]
Needs Formatting

**Comment by sourav2b** [comment]
I have done that in Clang formatter, but still it didn't...can you please help me out..what to do.

**Comment by amanv8060** [comment]
@sourav2b use google style for formatting , currently the style looks Like LLVM

**Comment by sourav2b** [comment]
Okay  thanks :)

**Comment by sourav2b** [comment]
Do JAVA needs formatting? can I do it in JAVA?

**Review by sourav2b — COMMENTED** [review]
Formatted with Google Style Formatting

**Pull request merged**
