### PR TITLE
Adding solution for {23}

### PR DESCRIPTION
**Pull request by shubhankit123**
Fixes #{Insert your issue number here}

My code sample is in : 
- [x] CPP
- [ ] Java 

Screenshot of working code sample  : 

## Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My code sample is formatted and works correctly 

[Contributor Guide]: https://github.com/amanv8060/Leetcode-Questions/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Comment by shubhankit123** [comment]
I am getting message as ! workflow awaiting approval, please approve it

**Comment by amanv8060** [comment]
Please update the pr comment , add issue number ,ss

**Comment by shubhankit123** [comment]
@amanv8060 I have already mentioned the issue number(23), what screeshot should I add?

**Comment by shubhankit123** [comment]
Bro, I have addede the screen shot, please check it, issue number is written ie 23

**Review by amanv8060 — COMMENTED** [review]
@shubhankit123 Thanks for your contribution. Please have a look at [this](https://github.com/amanv8060/Leetcode-Questions/pull/1736) pr, on how to edit the pr comment. Also, you need to format your code.

**Pull request closed without merging**
